server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/aivector
    username: ${POSTGRES_USER:ai}
    password: ${POSTGRES_PASSWORD:ai1234}

  data:
    mongodb:
#      host: localhost
#      port: 27017
      uri: mongodb://localhost:27017/mydb
      # 또는 개별 설정
      # host: localhost
      # port: 27017
      # database: mydb
  mongodb:
    uuid-representation: standard   # (권장) UUID 표준 표현
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-haiku
          temperature: 0.7
    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

